### ISSUE TITLE
no hungarian_assigner

### ISSUE THREAD

**Issue by wanghonglie** [microsoft/RelationNet2#10]
There is no hungarian_assigner in version c8511649550834ea168f610411a47a39cf194767 
The version in install.sh seems do not match

**Comment by wanghonglie** [comment]
and I can not find TRANSFORMER in any builder

**Comment by wanghonglie** [comment]
and from mmcv.cnn.bricks.transformer only works in mmcv>=1.3.0,but your mmdetection only support 1.1.3=<mmcv<=1.2

**Comment by sure7018** [comment]
您好，请问您解决mmcv的问题了吗

**Comment by wanghonglie** [comment]
> 您好，请问您解决mmcv的问题了吗
解决了，但我是用了2.9版本的mmdetection，装了对应的mmcv，然后一些报错的配置手动改了一下

**Comment by sure7018** [comment]
您好，因为在做这方面的课题，请问您成功跑通了吗，还有给的代码里包括了relation net 模块吗，还有错的配置多吗？谢谢您

**Comment by sure7018** [comment]
方便给个联系方式下面讨论一下吗

**Comment by sure7018** [comment]
您好，我已经跑通，但是想问一下您的训练时长如何，为何我在单GPU的服务器上，显示需要训练50天以上？？不知道您的训练时长是怎样？

**Comment by wanghonglie** [comment]
> 您好，我已经跑通，但是想问一下您的训练时长如何，为何我在单GPU的服务器上，显示需要训练50天以上？？不知道您的训练时长是怎样？

我还没有跑训练的，我只是下了作者的模型文件跑了测试

**Comment by JISLEE** [comment]
> > 您好，请问您解决mmcv的问题了吗
> > 解决了，但我是用了2.9版本的mmdetection，装了对应的mmcv，然后一些报错的配置手动改了一下

Hi, How did you use version 2.9.0?

**Comment by JISLEE** [comment]
@WangHonglie Hi, would you tell me which pytorch version, mmdet version and mmcv version you used for training?
